"""`sarbar setup`: source selection, .deb extraction, publishing, verification.

The falco half of this file is the interesting one. Falco stopped publishing
runnable binaries on GitHub — every release from 0.40.0 ships only a `.debug`
file, which cannot execute. Its official install script is deprecated and exits
1. The installer therefore reads the project's own Debian repository and
extracts the binary plus /etc/falco, which needs no root.
"""
from __future__ import annotations

import gzip
import io
import os
import pathlib
import shutil
import subprocess
import sys
import tarfile
import tempfile


from sarbar import setup as S


# ---------------------------------------------------------------- platform

def test_arch_mapping(monkeypatch):
    import platform
    monkeypatch.setattr(platform, "machine", lambda: "x86_64")
    assert S.get_arch() == "x86_64"
    monkeypatch.setattr(platform, "machine", lambda: "AMD64")
    assert S.get_arch() == "x86_64"
    monkeypatch.setattr(platform, "machine", lambda: "aarch64")
    assert S.get_arch() == "aarch64"
    monkeypatch.setattr(platform, "machine", lambda: "i686")
    assert S.get_arch() == "i386"


def test_os_mapping(monkeypatch):
    monkeypatch.setattr(sys, "platform", "linux")
    assert S.get_os() == "linux"
    monkeypatch.setattr(sys, "platform", "darwin")
    assert S.get_os() == "darwin"


def test_deb_arch_mapping(monkeypatch):
    monkeypatch.setattr(S, "get_arch", lambda: "x86_64")
    assert S.deb_arch() == "amd64"
    monkeypatch.setattr(S, "get_arch", lambda: "aarch64")
    assert S.deb_arch() == "arm64"


def test_layout_system_is_the_proper_linux_one():
    lay = S.Layout(system=True)
    assert lay.bin == "/usr/bin"
    assert lay.falco_etc == "/etc/falco"
    assert lay.data == "/var/lib/sarbar"


def test_layout_user_is_the_fallback(monkeypatch):
    monkeypatch.setenv("HOME", "/home/tester")
    lay = S.Layout(system=False)
    assert lay.bin == "/home/tester/.sarbar/bin"
    assert lay.falco_etc == "/home/tester/.sarbar/etc/falco"
    assert lay.data == "/home/tester/.sarbar"


def test_no_falco_wrapper_anywhere():
    """The 15-line shim is gone: falco is installed properly instead."""
    source = (pathlib.Path(__file__).parents[1] / "sarbar" / "setup.py").read_text()
    assert "FALCO_WRAPPER" not in source
    assert "Generated by `sarbar setup`" not in source


def test_publish_is_a_noop_in_the_system_layout():
    ok, where = S._publish("/usr/bin/trivy", "trivy", S.Layout(system=True))
    assert ok and where == "/usr/bin/trivy"


def test_skip_suffixes_exclude_debug():
    """.debug files must never be treated as installable."""
    for suffix in (".debug", ".sha256", ".asc", ".sigstore.json"):
        assert S.SKIP_SUFFIXES.count(suffix) == 1


# ---------------------------------------------------------------- trivy

def _release(assets):
    return {"tag_name": "v1.2.3", "assets": [
        {"name": n, "browser_download_url": f"https://example.invalid/{n}"}
        for n in assets]}


def test_trivy_picks_linux_amd64_tarball(monkeypatch):
    monkeypatch.setattr(S, "_fetch_json",
                        lambda url: _release(["trivy_1.2.3_Linux-64bit.tar.gz"]))
    got = S.trivy_asset()
    assert got == ("https://example.invalid/trivy_1.2.3_Linux-64bit.tar.gz", "1.2.3")


def test_trivy_rejects_debug_and_signatures(monkeypatch):
    monkeypatch.setattr(S, "_fetch_json", lambda url: _release([
        "trivy_1.2.3_Linux-64bit.tar.gz.debug",
        "trivy_1.2.3_checksums.txt",
        "trivy_1.2.3_Linux-64bit.tar.gz.sigstore.json",
    ]))
    assert S.trivy_asset() is None


def test_trivy_respects_arch(monkeypatch):
    monkeypatch.setattr(S, "get_arch", lambda: "aarch64")
    monkeypatch.setattr(S, "get_os", lambda: "linux")
    monkeypatch.setattr(S, "_fetch_json", lambda url: _release([
        "trivy_1.2.3_Linux-64bit.tar.gz", "trivy_1.2.3_Linux-ARM64.tar.gz"]))
    got = S.trivy_asset()
    assert got is not None
    assert got[0].endswith("Linux-ARM64.tar.gz")


def test_trivy_no_network(monkeypatch):
    def boom(url, timeout=30):
        raise OSError("no network")
    monkeypatch.setattr(S, "_fetch_json", boom)
    assert S.trivy_asset() is None


# ---------------------------------------------------------------- falco

PACKAGES = """\
Package: falco
Version: 0.42.1
Filename: stable/falco-0.42.1-x86_64.deb
Size: 51765712

Package: falco
Version: 0.39.2
Depends: dkms (>= 2.1.0.0)
Filename: stable/falco-0.39.2-x86_64.deb

Package: something-else
Version: 9.9.9
Filename: stable/other.deb
"""


def test_falco_index_parses_and_prefers_newest_without_dkms(monkeypatch):
    monkeypatch.setattr(S, "_get", lambda url, timeout=60: gzip.compress(PACKAGES.encode()))
    url, version = S.falco_deb()
    assert version == "0.42.1"
    assert url.endswith("falco-0.42.1-x86_64.deb")


def test_falco_index_skips_dkms_entries(monkeypatch):
    """.deb entries needing dkms need root and a compiler; skip them."""
    only_old = """Package: falco
Version: 0.39.2
Depends: dkms (>= 2.1.0.0)
Filename: stable/falco-0.39.2-x86_64.deb
"""
    monkeypatch.setattr(S, "_get",
                        lambda url, timeout=60: gzip.compress(only_old.encode()))
    assert S.falco_deb() is None


def test_falco_version_ordering():
    assert S._version_key("0.45.0") > S._version_key("0.9.0")
    assert S._version_key("0.42.1") > S._version_key("0.42.0")


def test_falco_no_network(monkeypatch):
    def boom(url, timeout=60):
        raise OSError("no network")
    monkeypatch.setattr(S, "_get", boom)
    assert S.falco_deb() is None


def test_falco_install_reports_the_real_reason_when_unreachable(tmp_path, monkeypatch):
    def boom(url, timeout=60):
        raise OSError("no network")
    monkeypatch.setattr(S, "_get", boom)
    lay = _StubLayout(tmp_path)
    msg = S.install_falco(lay)
    assert msg.startswith("failed")
    assert "only .debug since 0.40" in msg
    assert "deprecated" in msg


# ---------------------------------------------------------------- verify

def test_verify_accepts_a_runnable_binary(tmp_path):
    tool = tmp_path / "t"
    tool.write_text("#!/bin/sh\necho 'Version: 1.0'\n")
    tool.chmod(0o755)
    ok, detail = S.verify_binary(str(tool))
    assert ok and "Version" in detail


def test_verify_rejects_non_executable(tmp_path):
    """The old broken install: a .debug blob that cannot execute."""
    tool = tmp_path / "falco"
    tool.write_bytes(b"\x7fELF\x02\x01\x01" + b"\x00" * 200)
    tool.chmod(0o755)
    ok, detail = S.verify_binary(str(tool))
    assert not ok


def test_verify_rejects_non_zero_exit(tmp_path):
    tool = tmp_path / "t"
    tool.write_text("#!/bin/sh\nexit 3\n")
    tool.chmod(0o755)
    assert S.verify_binary(str(tool))[0] is False


def test_verify_reports_missing_file(tmp_path):
    ok, detail = S.verify_binary(str(tmp_path / "missing"))
    assert not ok


# ---------------------------------------------------------------- publish

_TMP = pathlib.Path(tempfile.mkdtemp())


def _lay(tmp_path):
    return _StubLayout(tmp_path)


def test_publish_creates_a_working_symlink(tmp_path, monkeypatch):
    lay = _lay(tmp_path)
    bindir = pathlib.Path(lay.local_bin)
    real = tmp_path / "trivy"
    real.write_text('#!/bin/sh\necho "Version: 1.0"\n')
    real.chmod(0o755)
    ok, where = S._publish(str(real), "trivy", lay)
    assert ok and where == str(bindir / "trivy")
    assert os.path.islink(where)
    out = subprocess.run([where, "--version"], capture_output=True, text=True)
    assert "Version" in out.stdout


def test_publish_replaces_an_existing_link(tmp_path, monkeypatch):
    lay = _lay(tmp_path)
    bindir = pathlib.Path(lay.local_bin)
    bindir.mkdir(parents=True, exist_ok=True)
    old = bindir / "trivy"
    old.write_text("stale")
    real = tmp_path / "trivy"
    real.write_text("#!/bin/sh\necho v\n")
    real.chmod(0o755)
    S._publish(str(real), "trivy", lay)
    assert os.path.realpath(old) == str(real)


def test_publish_reports_an_impossible_target(tmp_path, monkeypatch):
    monkeypatch.setattr(S.os, "makedirs",
                        lambda *a, **k: (_ for _ in ()).throw(PermissionError("nope")))
    ok, detail = S._publish("/bin/true", "trivy", _lay(tmp_path))
    assert not ok and "cannot create" in detail


def test_publish_never_touches_the_real_home(tmp_path):
    """Guards the install of the guard: the publish target must come from the
    layout, otherwise a test can overwrite the user's ~/.local/bin symlink."""
    lay = _lay(tmp_path)
    real = tmp_path / "trivy"
    real.write_text("#!/bin/sh\n")
    real.chmod(0o755)
    _ok, where = S._publish(str(real), "trivy", lay)
    assert str(tmp_path) in where


# ---------------------------------------------------------------- status

def test_engine_status_states(tmp_path, monkeypatch):
    import sarbar.engines as eng
    monkeypatch.setattr(eng, "SARBAR_BIN", str(tmp_path / "none"))

    monkeypatch.setattr(eng, "resolve", lambda name: None)
    assert S.engine_status("trivy") == ("absent", "not installed")

    blob = tmp_path / "blob"
    blob.write_bytes(b"\x7fELF broken")
    blob.chmod(0o755)
    monkeypatch.setattr(eng, "resolve", lambda name: str(blob))
    state, detail = S.engine_status("falco")
    assert state == "broken" and "does not run" in detail


# ---------------------------------------------------------------- hermetic

def test_setup_does_not_run_at_import():
    """I-10: importing sarbar.setup must not touch the network."""
    import importlib
    import sys
    for mod in list(sys.modules):
        if mod.startswith("sarbar"):
            del sys.modules[mod]
    calls = []
    real = S.urllib.request.urlretrieve
    module = importlib.import_module("sarbar.setup")
    module.urllib.request.urlretrieve = lambda url, dest: calls.append(url)
    assert calls == [], "import must not download anything"
    module.urllib.request.urlretrieve = real


def test_run_setup_is_offline_safe(monkeypatch, capsys):
    """With no network and nothing installed, the run must explain and not crash."""
    monkeypatch.setattr(S, "trivy_asset", lambda: None)
    monkeypatch.setattr(S, "falco_deb", lambda: None)
    monkeypatch.setattr(S, "Layout", lambda system=False: _StubLayout(_TMP))
    monkeypatch.setattr(S, "engine_status", lambda n: ("absent", "not installed"))
    monkeypatch.setattr(S, "falco_driver_state", lambda *a, **k: (False, "absent"))
    monkeypatch.setattr(S, "_docker_ok", lambda: False)
    assert S.run_setup([]) == 0
    out = capsys.readouterr().out
    assert "cannot reach" in out
    assert "only .debug since 0.40" in out
    assert "sarbar setup --check" in out


def test_run_setup_reports_already_installed(monkeypatch, capsys):
    """An existing working binary must not be downloaded again."""
    lay = _StubLayout(_TMP)
    monkeypatch.setattr(S, "Layout", lambda system=False: lay)
    pathlib.Path(lay.bin).mkdir(parents=True, exist_ok=True)
    for name in ("trivy", "falco", "falcoctl"):
        target = pathlib.Path(lay.bin) / name
        target.write_text("#!/bin/sh\necho Version: 9\n")
        target.chmod(0o755)
    pathlib.Path(lay.falco_etc).mkdir(parents=True, exist_ok=True)
    for f in ("falco.yaml", "falco_rules.yaml"):
        (pathlib.Path(lay.falco_etc) / f).write_text("x\n")
    pathlib.Path(lay.falco_plugins).mkdir(parents=True, exist_ok=True)
    (pathlib.Path(lay.falco_plugins) / "libcontainer.so").write_bytes(b"\x7fELF")
    monkeypatch.setattr(S, "engine_status", lambda n: ("ready", "somewhere"))
    monkeypatch.setattr(S, "falco_driver_state", lambda *a, **k: (True, "present"))
    monkeypatch.setattr(S, "_docker_ok", lambda: True)
    called = []
    monkeypatch.setattr(S, "trivy_asset", lambda: called.append("t"))
    monkeypatch.setattr(S, "falco_deb", lambda: called.append("f"))
    assert S.run_setup([]) == 0
    assert called == [], "must not look for downloads when binaries already work"
    assert "already" in capsys.readouterr().out


def test_run_setup_check_only_installs_nothing(monkeypatch, capsys):
    monkeypatch.setattr(S, "_docker_ok", lambda: False)
    called = []
    monkeypatch.setattr(S, "install_trivy", lambda *a, **k: called.append("t"))
    monkeypatch.setattr(S, "install_falco", lambda *a, **k: called.append("f"))
    assert S.run_setup(["--check"]) == 0
    assert called == [], "--check must not install anything"
    out = capsys.readouterr().out
    assert "state" in out and "trivy" in out and "falco" in out


def test_run_setup_only_selects_one(monkeypatch):
    calls = []
    monkeypatch.setattr(S, "install_trivy",
                        lambda *a, **k: (calls.append("t"), "ok")[1])
    monkeypatch.setattr(S, "install_falco",
                        lambda *a, **k: (calls.append("f"), "ok")[1])
    monkeypatch.setattr(S, "engine_status", lambda n: ("absent", "not installed"))
    monkeypatch.setattr(S, "falco_driver_state", lambda *a, **k: (False, "absent"))
    monkeypatch.setattr(S, "_docker_ok", lambda: False)
    S.run_setup(["--only", "falco"])
    assert calls == ["f"]

# ---------------------------------------------------------------- install flow

class _StubLayout(S.Layout):
    """Layout with every path redirected into a temp directory.

    local_bin matters most: without it a test would write a symlink into the
    real ~/.local/bin and clobber the user's installation.
    """

    def __init__(self, root):
        super().__init__(system=False)
        self.bin = str(root / "bin")
        self.etc = str(root / "etc")
        self.data = str(root / "data")

    @property
    def falco_etc(self):
        return os.path.join(self.etc, "falco")

    @property
    def local_bin(self):
        return os.path.join(self.data, "localbin")

    @property
    def local_share(self):
        return os.path.join(self.data, "share")


def _tarball_with(path, member, payload):
    with tarfile.open(path, "w:gz") as tar:
        info = tarfile.TarInfo(member)
        info.size = len(payload)
        tar.addfile(info, io.BytesIO(payload))
    return str(path)


def _stub_download(monkeypatch, src):
    monkeypatch.setattr(S, "_download",
                        lambda url, dest, timeout=0: shutil.copy(src, dest))


def test_install_trivy_extracts_verifies_and_publishes(tmp_path, monkeypatch):
    lay = _StubLayout(tmp_path)
    payload = b'#!/bin/sh\necho "Version: 0.99.0"\n'
    archive = _tarball_with(tmp_path / "t.tar.gz", "trivy", payload)
    monkeypatch.setattr(S, "trivy_asset",
                        lambda: ("https://example.invalid/t", "0.99.0"))
    _stub_download(monkeypatch, archive)
    msg = S.install_trivy(lay)
    assert msg.startswith("ok")
    assert (tmp_path / "bin" / "trivy").read_bytes() == payload
    assert os.access(tmp_path / "bin" / "trivy", os.X_OK)
    # and the symlink landed in the temp dir, not in the real ~/.local/bin
    assert pathlib.Path(lay.local_bin).joinpath("trivy").is_symlink()


def test_install_trivy_keeps_a_working_binary(tmp_path, monkeypatch):
    lay = _StubLayout(tmp_path)
    good = tmp_path / "bin" / "trivy"
    good.parent.mkdir(parents=True, exist_ok=True)
    good.write_text('#!/bin/sh\necho "Version: 1.0"\n')
    good.chmod(0o755)
    assert S.install_trivy(lay).startswith("already")


def test_install_trivy_replaces_a_broken_binary(tmp_path, monkeypatch):
    lay = _StubLayout(tmp_path)
    broken = tmp_path / "bin" / "trivy"
    broken.parent.mkdir(parents=True, exist_ok=True)
    broken.write_bytes(b"\x7fELF broken")
    broken.chmod(0o755)
    payload = b'#!/bin/sh\necho "Version: 2.0"\n'
    archive = _tarball_with(tmp_path / "t.tar.gz", "trivy", payload)
    monkeypatch.setattr(S, "trivy_asset",
                        lambda: ("https://example.invalid/t", "2.0"))
    _stub_download(monkeypatch, archive)
    assert S.install_trivy(lay).startswith("ok")
    assert broken.read_bytes() == payload


def test_install_trivy_deletes_a_file_that_cannot_run(tmp_path, monkeypatch):
    lay = _StubLayout(tmp_path)
    payload = b"\x7fELF not runnable at all"
    archive = _tarball_with(tmp_path / "t.tar.gz", "trivy", payload)
    monkeypatch.setattr(S, "trivy_asset",
                        lambda: ("https://example.invalid/t", "3.0"))
    _stub_download(monkeypatch, archive)
    assert S.install_trivy(lay).startswith("broken")
    assert not (tmp_path / "bin" / "trivy").exists()


def test_install_trivy_reports_download_failure(tmp_path, monkeypatch):
    lay = _StubLayout(tmp_path)
    monkeypatch.setattr(S, "trivy_asset",
                        lambda: ("https://example.invalid/t", "1.0"))

    def boom(url, dest, timeout=0):
        raise OSError("network down")

    monkeypatch.setattr(S, "_download", boom)
    assert "failed to download" in S.install_trivy(lay)


def test_install_trivy_rejects_archive_without_binary(tmp_path, monkeypatch):
    lay = _StubLayout(tmp_path)
    archive = _tarball_with(tmp_path / "t.tar.gz", "README", b"nothing here")
    monkeypatch.setattr(S, "trivy_asset",
                        lambda: ("https://example.invalid/t", "1.0"))
    _stub_download(monkeypatch, archive)
    assert "does not contain" in S.install_trivy(lay)


def test_install_falco_reports_the_real_world_cause(tmp_path, monkeypatch):
    """The message must name the actual upstream problem, not a generic error."""
    lay = _StubLayout(tmp_path)
    monkeypatch.setattr(S, "falco_deb", lambda: None)
    msg = S.install_falco(lay)
    assert "only .debug since 0.40" in msg
    assert "falco.org/script/install is deprecated" in msg


def test_install_falco_needs_an_extractor(tmp_path, monkeypatch):
    lay = _StubLayout(tmp_path)
    monkeypatch.setattr(S, "falco_deb",
                        lambda: ("https://example.invalid/f.deb", "0.42.1"))
    deb = tmp_path / "f.deb"
    deb.write_bytes(b"not really a deb")
    _stub_download(monkeypatch, deb)
    monkeypatch.setattr(S.shutil, "which", lambda n: None)
    msg = S.install_falco(lay)
    assert "could not extract" in msg
    assert "dpkg-deb or ar" in msg


def test_install_falco_copies_config_next_to_the_binary(tmp_path, monkeypatch):
    """Without /etc/falco the binary refuses to start; config must travel — and
    so must falcoctl and the container plugin, or falco runs but sees nothing."""
    lay = _StubLayout(tmp_path)
    payload = b'#!/bin/sh\necho "Falco version: 9.9"\n'
    archive = _tarball_with(tmp_path / "f.tar.gz", "falco", payload)
    conf = _tarball_with(tmp_path / "c.tar.gz", "etc/falco/falco.yaml", b"rules_file: /x\n")
    monkeypatch.setattr(S, "falco_deb",
                        lambda: ("https://example.invalid/f.deb", "9.9"))
    calls = {"n": 0}

    def fake_download(url, dest, timeout=0):
        calls["n"] += 1
        shutil.copy(archive if calls["n"] == 1 else conf, dest)
        return dest

    monkeypatch.setattr(S, "_download", fake_download)
    monkeypatch.setattr(S, "_extract_deb",
                        lambda deb, root: _fake_falco_tree(root, payload))
    msg = S.install_falco(lay)
    assert msg.startswith("ok"), msg
    assert (tmp_path / "etc" / "falco" / "falco.yaml").is_file()
    assert (tmp_path / "etc" / "falco" / "falco_rules.yaml").is_file()


def test_extract_deb_prefers_dpkg_deb(tmp_path, monkeypatch):
    seen = {}

    def fake_run(cmd, **kw):
        seen["cmd"] = cmd
        root = cmd[3]
        os.makedirs(os.path.join(root, "usr", "bin"))
        with open(os.path.join(root, "usr", "bin", "falco"), "w") as fh:
            fh.write("x")
        return subprocess.CompletedProcess(cmd, 0)

    monkeypatch.setattr(S.shutil, "which",
                        lambda n: "/usr/bin/dpkg-deb" if n == "dpkg-deb" else None)
    monkeypatch.setattr(subprocess, "run", fake_run)
    got = S._extract_deb(str(tmp_path / "x.deb"), str(tmp_path / "root"))
    assert got and got.endswith("usr/bin/falco")
    assert seen["cmd"][0] == "dpkg-deb"


# ---------------------------------------------------------------- root-only bits

def test_system_layout_without_root_is_refused(monkeypatch, capsys):
    monkeypatch.setattr(S, "is_root", lambda: False)
    assert S.run_setup(["--system"]) == 1
    assert "needs root" in capsys.readouterr().out


def test_driver_install_requires_root(monkeypatch):
    monkeypatch.setattr(S, "is_root", lambda: False)
    ok, detail = S.install_falco_driver()
    assert not ok and "sudo sarbar setup --driver" in detail


def test_system_install_touches_system_paths(tmp_path, monkeypatch):
    """With --system the binaries must land in /usr/bin, not in ~/.sarbar."""
    lay = S.Layout(system=True)
    assert lay.bin == "/usr/bin"
    assert lay.falco_etc == "/etc/falco"
    ok, where = S._publish("/usr/bin/falco", "falco", S.Layout(system=True))
    assert ok and where == "/usr/bin/falco", "no shim, no symlink, just the path"


# ------------------------------------------------- the two falco install holes

def test_falco_installation_must_include_falcoctl(tmp_path, monkeypatch):
    """Without falcoctl there is no way to install the driver at all."""
    lay = _StubLayout(tmp_path)
    pathlib.Path(lay.bin).mkdir(parents=True, exist_ok=True)
    (pathlib.Path(lay.bin) / "falco").write_text('#!/bin/sh\necho "Falco version: 9"\n')
    (pathlib.Path(lay.bin) / "falco").chmod(0o755)
    pathlib.Path(lay.falco_plugins).mkdir(parents=True, exist_ok=True)
    (pathlib.Path(lay.falco_plugins) / "libcontainer.so").write_bytes(b"\x7fELF")
    missing = S._falco_missing(lay)
    assert any("falcoctl" in m for m in missing), missing


def test_falco_installation_must_include_the_container_plugin(tmp_path):
    """Without libcontainer.so falco exits with "Plugin requirement not
    satisfied" and can never observe a container."""
    lay = _StubLayout(tmp_path)
    pathlib.Path(lay.bin).mkdir(parents=True, exist_ok=True)
    (pathlib.Path(lay.bin) / "falcoctl").write_text("x")
    missing = S._falco_missing(lay)
    assert any("plugin" in m for m in missing), missing


def test_a_complete_falco_install_has_nothing_missing(tmp_path):
    lay = _StubLayout(tmp_path)
    pathlib.Path(lay.bin).mkdir(parents=True, exist_ok=True)
    (pathlib.Path(lay.bin) / "falcoctl").write_text("x")
    pathlib.Path(lay.falco_plugins).mkdir(parents=True, exist_ok=True)
    (pathlib.Path(lay.falco_plugins) / "libcontainer.so").write_bytes(b"\x7fELF")
    assert S._falco_missing(lay) == []


def test_incomplete_falco_is_reinstalled_not_declared_ready(tmp_path, monkeypatch):
    """A half-installed falco looks working and is worse than none: it reports
    '0 events' instead of an error."""
    lay = _StubLayout(tmp_path)
    pathlib.Path(lay.bin).mkdir(parents=True, exist_ok=True)
    (pathlib.Path(lay.bin) / "falco").write_text('#!/bin/sh\necho "Falco version: 1"\n')
    (pathlib.Path(lay.bin) / "falco").chmod(0o755)
    payload = b'#!/bin/sh\necho "Falco version: 2"\n'
    archive = _tarball_with(tmp_path / "f.tar.gz", "falco", payload)
    monkeypatch.setattr(S, "falco_deb",
                        lambda: ("https://example.invalid/f.deb", "2"))
    _stub_download(monkeypatch, archive)
    monkeypatch.setattr(S, "_extract_deb", lambda deb, root: _fake_falco_tree(root, payload))
    assert S.install_falco(lay).startswith("ok")
    assert os.path.isfile(os.path.join(lay.bin, "falcoctl"))
    assert os.path.isfile(os.path.join(lay.falco_plugins, "libcontainer.so"))


def _fake_falco_tree(root, payload):
    os.makedirs(os.path.join(root, "usr", "bin"), exist_ok=True)
    os.makedirs(os.path.join(root, "etc", "falco"), exist_ok=True)
    os.makedirs(os.path.join(root, "usr", "share", "falco", "plugins"), exist_ok=True)
    with open(os.path.join(root, "usr", "bin", "falco"), "wb") as fh:
        fh.write(payload)
    with open(os.path.join(root, "usr", "bin", "falcoctl"), "wb") as fh:
        fh.write(b'#!/bin/sh\necho "falcoctl 2"\n')
    for name in ("falco.yaml", "falco_rules.yaml"):
        with open(os.path.join(root, "etc", "falco", name), "w") as fh:
            fh.write("x\n")
    with open(os.path.join(root, "usr", "share", "falco", "plugins",
                           "libcontainer.so"), "wb") as fh:
        fh.write(b"\x7fELF plugin")
    return os.path.join(root, "usr", "bin", "falco")


def test_driver_install_refuses_when_the_install_is_incomplete(tmp_path, monkeypatch):
    """Reporting 'driver not installed' without saying WHY would hide the hole."""
    lay = _StubLayout(tmp_path)
    monkeypatch.setattr(S, "is_root", lambda: True)
    monkeypatch.setattr(S, "falcoctl_path", lambda *a, **k: os.path.join(lay.bin, "falcoctl"))
    ok, detail = S.install_falco_driver(lay)
    assert not ok
    assert "incomplete" in detail and "plugin" in detail


def test_driver_state_reports_the_hole_instead_of_a_optimistic_yes(tmp_path):
    lay = _StubLayout(tmp_path)
    monkeypatch_ok, detail = S.falco_driver_state(lay)
    assert not monkeypatch_ok
    assert "falcoctl" in detail
